version: "3.2"
services:

  sql-server-db:
    container_name: sql-server-db #nome do container a ser criado
    image: mcr.microsoft.com/mssql/server:2022-latest
    ports:
      - "1433:1433"
    environment:
      SA_PASSWORD: "change_this_password"
      ACCEPT_EULA: "Y"